version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=dev
    depends_on:
      - database

  web:
    image: nginx:alpine
    container_name: symfony_web
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: symfony_database
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
    volumes:
      - database_data:/var/lib/postgresql/data:rw

volumes:
  database_data:
